{{- if .Values.taskmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taskmanager.serviceAccount" . }}
{{- if .Values.taskmanager.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .Values.taskmanager.serviceAccount.annotations) . | indent 4 }}
{{- end }}
  labels:
{{ include "flink.labels" . | indent 4 }}
{{- end }}
